const database = [
    {
        id: 1,
        firstName: "حسين",
        fatherName: "أحمد",
        lastName: "الفارس",
        fullName: "حسين أحمد الفارس",
        nationalNumber: "111080065381",
        idCard: "1234567890",
        birthDate: "01/01/1989",
        address: "الرقة — تل أبيض",
        phone: "+963932304537",
        taxNumber: "111080065381",
        nationality: "سوري",
        gender: "ذكر"
    },
    {
        id: 2,
        firstName: "معتز",
        fatherName: "محمد",
        lastName: "الفارس",
        fullName: "معتز محمد الفارس",
        nationalNumber: "111080065382",
        idCard: "1234567891",
        birthDate: "15/05/1992",
        address: "الرقة — مركز المدينة",
        phone: "+963932304538",
        taxNumber: "111080065382",
        nationality: "سوري",
        gender: "ذكر"
    },
    {
        id: 3,
        firstName: "سامر",
        fatherName: "علي",
        lastName: "الحسن",
        fullName: "سامر علي الحسن",
        nationalNumber: "110012345678",
        idCard: "1122334455",
        birthDate: "10/03/1985",
        address: "دمشق — الميدان",
        phone: "+963955123456",
        taxNumber: "110012345678",
        nationality: "سوري",
        gender: "ذكر"
    },
    { id: 101, firstName: "محمد", lastName: "الأحمد", fullName: "محمد الأحمد", nationality: "سوري", gender: "ذكر" },
    { id: 102, firstName: "محمد", lastName: "علي", fullName: "محمد علي", nationality: "سوري", gender: "ذكر" },
    { id: 103, firstName: "أحمد", lastName: "حسن", fullName: "أحمد حسن", nationality: "سوري", gender: "ذكر" },
    { id: 104, firstName: "أحمد", lastName: "المحمد", fullName: "أحمد المحمد", nationality: "سوري", gender: "ذكر" },
    { id: 105, firstName: "علي", lastName: "سليمان", fullName: "علي سليمان", nationality: "سوري", gender: "ذكر" },
    { id: 106, firstName: "حسين", lastName: "علي", fullName: "حسين علي", nationality: "سوري", gender: "ذكر" },
    { id: 107, firstName: "حسن", lastName: "حسين", fullName: "حسن حسين", nationality: "سوري", gender: "ذكر" },
    { id: 108, firstName: "يوسف", lastName: "أحمد", fullName: "يوسف أحمد", nationality: "سوري", gender: "ذكر" },
    { id: 109, firstName: "عمر", lastName: "محمد", fullName: "عمر محمد", nationality: "سوري", gender: "ذكر" },
    { id: 110, firstName: "خالد", lastName: "علي", fullName: "خالد علي", nationality: "سوري", gender: "ذكر" },
    { id: 111, firstName: "سارة", lastName: "الأحمد", fullName: "سارة الأحمد", nationality: "سورية", gender: "أنثى" },
    { id: 112, firstName: "مريم", lastName: "حسن", fullName: "مريم حسن", nationality: "سورية", gender: "أنثى" },
    { id: 113, firstName: "فاطمة", lastName: "علي", fullName: "فاطمة علي", nationality: "سورية", gender: "أنثى" },
    { id: 114, firstName: "نور", lastName: "المحمد", fullName: "نور المحمد", nationality: "سورية", gender: "أنثى" },
    { id: 115, firstName: "هدى", lastName: "سليمان", fullName: "هدى سليمان", nationality: "سورية", gender: "أنثى" },
    { id: 116, firstName: "سامر", lastName: "إبراهيم", fullName: "سامر إبراهيم", nationality: "سوري", gender: "ذكر" },
    { id: 117, firstName: "تامر", lastName: "محمد", fullName: "تامر محمد", nationality: "سوري", gender: "ذكر" },
    { id: 118, firstName: "باسم", lastName: "علي", fullName: "باسم علي", nationality: "سوري", gender: "ذكر" },
    { id: 119, firstName: "راما", lastName: "أحمد", fullName: "راما أحمد", nationality: "سورية", gender: "أنثى" },
    { id: 120, firstName: "سمر", lastName: "حسن", fullName: "سمر حسن", nationality: "سورية", gender: "أنثى" },
    { id: 121, firstName: "ليلى", lastName: "علي", fullName: "ليلى علي", nationality: "سورية", gender: "أنثى" },
    { id: 122, firstName: "منى", lastName: "المحمد", fullName: "منى المحمد", nationality: "سورية", gender: "أنثى" },
    { id: 123, firstName: "جمال", lastName: "عمر", fullName: "جمال عمر", nationality: "سوري", gender: "ذكر" },
    { id: 124, firstName: "حامد", lastName: "سليم", fullName: "حامد سليم", nationality: "سوري", gender: "ذكر" },
    { id: 125, firstName: "زينب", lastName: "أحمد", fullName: "زينب أحمد", nationality: "سورية", gender: "أنثى" }
];
